### ISSUE TITLE
Hi discord link not working can you update?

### ISSUE THREAD

**Issue by duythien0912** [zyairelai/long-term-low-leverage#1]
Hi discord link not working can you update?

**Comment by zyairelai** [comment]
It is working, did you quit the Discord group before? I coded a bot that auto bans those who quited

**Comment by duythien0912** [comment]
Yes. Can I join again I was follow you a long time ago

**Comment by zyairelai** [comment]
Only 1 time as exception ya, next time i will be lazy to revoke the ban 😒

**Comment by duythien0912** [comment]
so new account will oke then ?
